services:
  service-discovery:
    build: .
    image: panomete-service-discovery
    container_name: panomete-service-discovery
    restart: always
    ports:
      - "8761:8761"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true